server:
  port: 8085
spring:
  application:
    name: api-gateway-monolith
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product_route
          uri: lb://PRODUCT-SERVICE-MONOLITH
          predicates:
            - Path=/api/products/**
        - id: order_route
          uri: lb://ORDER-SERVICE-MONOLITH
          predicates:
            - Path=/api/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


