server:
  port: 8085

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product_route
          uri: lb://PRODUCT-SERVICE-MONOLITH
          predicates:
            - Path=/api/products/**
        - id: order_route
          uri: lb://ORDER-SERVICE-MONOLITH
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka



