server:
  port: 8085
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product_route
          uri: lb://product-service-monolith
          predicates:
            - Path=/api/products/**
        - id: order_route
          uri: lb://order-service-monolith
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


