server:
  port: 8082

spring:
  application:
    name: order-service-monolith

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: Ajayv@10
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5  
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


resilience4j:
  circuitbreaker:
    instances:
      productServiceCB:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s  
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        register-health-indicator: true
        ignore-exceptions:
          - com.example.order_service_monolith.exception.ProductNotFoundException
          - java.lang.RuntimeException  

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        retryer: feign.Retryer.Default
